Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,7 +29,14 @@ jobs:
       run: |
         for i in {1..60}
         do
-          if curl -s https://node-ga-${{ github.run_id }}.herokuapp.com | grep -q OK...
+          result=$(curl -s https://node-ga-${{ github.run_id }}.herokuapp.com)
+        
+          if echo "$result" | grep -q 'Application Error'
+          then
+            exit 1
+          fi
+        
+          if echo "$result" | grep -q 'OK...'
           then
             exit 0
           fi
